name: Test CI/CD Pipeline
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        run: echo "${{ toJson(github.event) }}"
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.4'
      - name: Run tests
        run: go test -v ./...


  
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.4'
      - name: Build the application
        run: go build -v ./...
  
 

 
